name: travelin
description: "A aplication mobile project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4     # Si usarás autenticación
  cloud_firestore: ^4.0.0     # Si usarás Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.1.0 


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Finlandica
      fonts:
        - asset: assets/fonts/finlandica/Finlandica-SemiBold.ttf