// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrwWfWoZMrOryPWTCQToiWDH-8dPY9nWU',
    appId: '1:1449629575:web:ed8fdbd19fbca243ed6522',
    messagingSenderId: '1449629575',
    projectId: 'aplicacionesmovilesusm',
    authDomain: 'aplicacionesmovilesusm.firebaseapp.com',
    storageBucket: 'aplicacionesmovilesusm.firebasestorage.app',
    measurementId: 'G-PWK664LQ52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ci9BronQ7OgaIqCWHNiA8GcSxN81rZg',
    appId: '1:1449629575:android:42894ef4a80d9470ed6522',
    messagingSenderId: '1449629575',
    projectId: 'aplicacionesmovilesusm',
    storageBucket: 'aplicacionesmovilesusm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8R3Vivf2xH2uzzSdDXMvYa4SCAdn1rg',
    appId: '1:1449629575:ios:c60150f868ba4399ed6522',
    messagingSenderId: '1449629575',
    projectId: 'aplicacionesmovilesusm',
    storageBucket: 'aplicacionesmovilesusm.firebasestorage.app',
    iosBundleId: 'com.example.app0',
  );
}
